spring:
  flyway:
    enabled: false
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    username: sa
    url: jdbc:h2:mem:test;MODE=MYSQL
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
fcm:
  json:
    path: config/pium-fcm.json

petPlant:
  image:
    directory: test
dictPlant:
  image:
    directory: /dict
server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
  slack:
    webhook-url: https://WEB_HOOK_URL.com
admin:
  secondPassword: 123
  password: 123
  account: asdf
aws:
  s3:
    root: https://test.image.storage
    directory: test
    folder: test/
    bucket: test/

local:
  image:
    root: src/test/resources
    web: https://static.pium.life
auth:
  kakao:
    member-info-request-uri: https://kapi.kakao.com/v2/user/me
    unlink-uri: https://kapi.kakao.com/v1/user/unlink
    redirect-uri: http://localhost:8282/authorization
    client-id: REST_API_KEY
    token-request-uri: https://kauth.kakao.com/oauth/token
    admin-id: ADMIN_KEY
registration:
  image:
    directory: registration
view:
  image:
    favicion: https://static.pium.life/prod/favicon.ico
    home: https://static.pium.life/prod/home.png
