openapi: 3.0.3
info:
  title: Pium API Document
  description: |-
    Pium Application API Document
  version: 1.0.0
servers:
  - url: https://api.piuml.life
tags:
  - name: dictionary-plants
    description: 사전 식물 관련 API
  - name: pet-plants
    description: 반려 식물 관련 API
  - name: member
    description: 사용자 관련 API
  - name: history
    description: 타임라인 관련 API
  - name: reminder
    description: 리마인더 관련 API
  - name: auth
    description: 인증 관련 API
paths:
  '/dictionary-plants/{id}':
    get:
      tags:
        - dictionary-plants
      summary: '반려식물 단건 조회'
      parameters:
        - name: id
          in: path
          description: 사전 식물 고유 ID
          required: true
          schema:
            type: integer
            format: integer64
      responses:
        '200':
          description: 요청 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DictionaryPetPlant'
        '404':
          description: 'Not Found'
  '/dictionary-plants':
    get:
      tags:
        - dictionary-plants
      summary: '반려식물 이름으로 조회'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DictionaryPetPlantsBySearch'
        '404':
          description: 'Not Found'

  '/pet-plants':
    get:
      tags:
        - pet-plants
      summary: 반려 식물 목록 조회
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          description: 요청 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetPlants'
        '201':
          description: 요청 성공
          content:
            application/json:
              schema:
                properties:
                  hello:
                    type: string
                    example: dd
    post:
      tags:
        - pet-plants
      summary: 반려 식물 목록 조회
      requestBody:
        description: '반려 식물 생성 요청'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetPlantCreate'
      responses:
        '201':
          description: '요청 성공'
  '/pet-plants/{id}':
    get:
      tags:
        - pet-plants
      summary: 반려 식물 목록 조회
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          description: 사전 식물 고유 ID
          required: true
          schema:
            type: integer
            format: integer64
      responses:
        '200':
          description: 요청 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetPlant'
    patch:
      tags:
        - pet-plants
      summary: 반려 식물 단건 수정
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          description: 사전 식물 고유 ID
          required: true
          schema:
            type: integer
            format: integer64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePetPlant'
      responses:
        '200':
          description: 요청 성공

    delete:
      tags:
        - pet-plants
      summary: 반려 식물 단건 삭제
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          description: 반려 식물 고유 ID
          required: true
          schema:
            type: integer
            format: integer64
      responses:
        '204':
          description: 요청 성공

  '/reminders':
    get:
      tags:
        - reminder
      summary: '리마인더 조회'
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          description: 요청 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reminder'
  '/reminders/{petPlantId}':
    post:
      tags:
        - reminder
      summary: '리마인더 조회'
      parameters:
        - name: petPlantId
          in: path
          description: 반려 식물 고유 ID
          required: true
          schema:
            type: integer
            format: integer64
      security:
        - cookieAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReminderWater'
      responses:
        '201':
          description: 요청 성공
    patch:
      tags:
        - reminder
      summary: '리마인더 조회'
      security:
        - cookieAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReminderChangeDate'
      responses:
        '200':
          description: 요청 성공

  '/history':
    get:
      tags:
        - history
      summary: '반려 식물 타임라인 조회'
      security:
        - cookieAuth: [ ]
      parameters:
        - name: petPlantId
          in: query
          description: 반려 식물 고유 번호
          required: true
          schema:
            type: integer
            format: integer64
        - name: page
          in: query
          description: '페이지 번호 (0부터 시작)'
          schema:
            type: integer
            format: integer64
        - name: size
          in: query
          description: 한 페이지 데이터 개수
          required: false
          schema:
            type: integer
            format: integer64
        - name: filter
          in: query
          description: 필터링 정보
          required: false
          schema:
            type: string
            example: 'lastWaterDate,waterCycle,flowerpot,wind,light,location'
      responses:
        '200':
          description: 요청 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetPlantHistory'

  '/members/me':
    get:
      tags:
        - member
      summary: '유효 세션 확인'
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          description: 인증 성공
        '401':
          description: 인증 실패
  '/members/withdraw':
    post:
      tags:
        - member
      summary: '회원 탈퇴'
      security:
        - cookieAuth: [ ]
      responses:
        '204':
          description: 탈퇴 성공
  '/login':
    post:
      tags:
        - auth
      summary: '로그인'
      security:
        - cookieAuth: [ ]
      parameters:
        - name: code
          in: query
          description: 로그인 코드 정보
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 요청 성공
  '/logout':
    post:
      tags:
        - auth
      summary: '로그아웃'
      security:
        - cookieAuth: [ ]
      responses:
        '200':
          description: 요청 성공
components:
  schemas:
    DictionaryPetPlantsBySearch:
      title: 'DictionaryPetPlantsBySearch'
      description: '사전 식물 검색 결과'
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 1
              name:
                type: string
                example: 아카시아
              image:
                type: string
                example: 'https://image.com'
    DictionaryPetPlant:
      title: 'DictionaryPetPlant'
      description: '사전 식물 기본 정보'
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: 다육이
        image:
          type: string
          example: 'https://image.com'
        familyName:
          type: string
          example:
            example: '백합과'
        smell:
          type: string
          example: '거의 없음'
        poison:
          type: string
          example: '있음'
        manageLevel:
          type: string
          example: '초보자'
        growSpeed:
          type: string
          example: '보통'
        requireTemp:
          type: string
          example: '16~20도'
        minimumTemp:
          type: string
          example: '13도 이상'
        requireHumidity:
          type: string
        postingPlace:
          type: array
          example: [ '실내 어두운 곳', '거실 내측', '거실 창측', '발코니 내측' ]
        waterCycle:
          properties:
            spring:
              type: string
              example: '흙을 촉촉하게 유지 (물에 잠기지 않도록)'
            summer:
              type: string
              example: '흙을 촉촉하게 유지 (물에 잠기지 않도록)'
            autumn:
              type: string
              example: '흙을 촉촉하게 유지 (물에 잠기지 않도록)'
            winter:
              type: string
              example: '흙을 촉촉하게 유지 (물에 잠기지 않도록)'
    PetPlant:
      title: 'PetPlant'
      description: '반려 식물 정보'
      properties:
        id:
          type: integer
          example: 1
        nickname:
          type: string
          example: '나의 아카시아(별명)'
        imageUrl:
          type: string
          example: 'https://image.com'
        dictionaryPlant:
          type: object
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: '아카시아'
        location:
          type: string
          example: '거실'
        flowerpot:
          type: string
          example: '플라스틱'
        light:
          type: string
          example: '창 밖'
        wind:
          type: string
          example: '바람이 안통해요'
        birthDate:
          type: string
          example: '2000-01-08'
        lastWaterDate:
          type: string
          example: '2023-07-10'
        secondLastWaterDate:
          type: string
          example: '2023-07-10'
        waterCycle:
          type: integer
          example: 3
        dday:
          type: integer
          example: 10
        daySince:
          type: integer
          example: 2341
        nextWaterDate:
          type: string
          example: '2023-07-10'
    PetPlants:
      title: 'PetPlants'
      description: '반려 식물 목록 정보'
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 2
              nickname:
                type: string
                example: '기영이'
              imageUrl:
                type: string
                example: 'https://image.com'
              dictionaryPlantName:
                type: string
                example: '스투키'
              birthDate:
                type: string
                example: '2023-07-08'
              daySince:
                type: integer
                example: 95
    UpdatePetPlant:
      properties:
        nickname:
          type: string
          example: '기영이'
        flowerpot:
          type: string
          example: '플라스틱'
        waterCycle:
          type: integer
          example: 3
        light:
          type: string
          example: '창 밖'
        location:
          type: string
          example: '욕실'
        wind:
          type: string
          example: '바람이 안통해요'
        birthDate:
          type: string
          example: '2003-07-08'
        lastWaterDate:
          type: string
          example: '2023-07-10'
    PetPlantHistory:
      title: 'PetPlantHistory'
      description: '반려 식물 타임라인 단건 조회 결과'
      properties:
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 10
        elementSize:
          type: integer
          example: 235
        hasNext:
          type: boolean
          example: true
        data:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: 'lastWaterDate'
              date:
                type: string
                example: '2023-07-01'
              content:
                type: object
                properties:
                  previous:
                    type: string
                    example: 'EMPTY'
                  current:
                    type: string
                    example: '2023-07-01'
    Reminder:
      title: 'Reminder'
      description: '리마인더 조회 정보'
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              petPlantId:
                type: integer
                example: 1
              image:
                type: string
                example: 'image.com'
              nickName:
                type: string
                example: '참새나무'
              dictionaryPlantName:
                type: string
                example: '알로카시아'
              dday:
                type: integer
                example: 3
              nextWaterDate:
                type: string
                example: '2023-07-07'
              lastWaterDate:
                type: string
                example: '2023-07-16'
    PetPlantCreate:
      title: 'PetPlantCreate'
      description: '반려식물 생성 정보'
      properties:
        dictionaryPlantId:
          type: integer
          example: 1
        nickname:
          type: string
          example: "기영이"
        location:
          type: string
          example: "거실"
        flowerpot:
          type: string
          example: "플라스틱"
        waterCycle:
          type: integer
          example: 7
        light:
          type: string
          example: "창 밖"
        wind:
          type: string
          example: "바람이 안통해요"
        birthDate:
          type: string
          example: "2023-07-08"
        lastWaterDate:
          type: string
          example: "2023-07-10"
    ReminderWater:
      properties:
        waterDate:
          type: string
          example: '2023-06-12'
    ReminderChangeDate:
      properties:
        nextWaterDate:
          type: string
          example: '2023-06-12'
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID  # cookie name
